### ISSUE TITLE
how many channels required/preferable for ICA?

### ISSUE THREAD

**Issue by nicoa47** [nicoa47/LDEEG#17]
see Mattermost:

> - pro low-channel ICA: https://pubmed.ncbi.nlm.nih.gov/26738010/ (as low as 3 channels)
> - ...there was an article presenting an adapted ICA algo for few channels, can't find right now...
> - naive idea: might it work to derive more components via interpolating pseudo-channels in between the real channels of a low-density setup? then one might upscale a layout from e.g. 6 channels to e.g. 12 (so adding 6 "virtual" channels). However, I don't know whether it messes with ICA that these "virtual" channels are just functions of other neighbouring channels.

**Comment by caghangir-1** [comment]
We will not use ICA.

**Comment by nicoa47** [comment]
agree --> not a planned analysis anymore
