### ISSUE TITLE
measures to quantify generic SNR of EEG data

### ISSUE THREAD

**Issue by nicoa47** [nicoa47/LDEEG#18]
scrape criteria from automatic EEG cleaning pipelines
- Automagic
- https://digyt.github.io/automated_EEG_cleaning_comparison/

**Comment by caghangir-1** [comment]
We will never use Automagic man, pyPREP does the job way clearer already. So, we can close this issue.

**Comment by nicoa47** [comment]
this is not about Automagic, but it is tied to issue #15 , which is not planned anymore. So yes, --> close.
