### ISSUE TITLE
auto-generate hypnograms for all files

### ISSUE THREAD

**Issue by nicoa47** [nicoa47/LDEEG#20]
YASA parameters (channel, preprocessing, ...): 
- see [wiki](https://github.com/Action-Control-in-Sleep/LDEEG/wiki/tools#yasa)

**Comment by caghangir-1** [comment]
I see that you self-destroyed yourself here. Why to sleep score the incredibly noisy, fucked up big LD  data we have with low trust in AI-based outcomes (our data is similar to fraud compared to the big sleep dataset YASA modules have been trained). Even jumping to some other methods just gives you burden us for nothing. Our data is already scored and I further validated it multiple times per data.

**Comment by nicoa47** [comment]
yep, unfortunately wasted lot of time here.
