### ISSUE TITLE
implement minimal cleaning pipeline

### ISSUE THREAD

**Issue by nicoa47** [nicoa47/LDEEG#21]
6. notch filter (read first: https://doi.org/10.1016/j.neuron.2019.02.039 )
> If the high-frequency region is not of interest, a simple expedient is to apply a boxcar smoothing kernel of size 1/50 Hz (or 1/60 Hz as appropriate)
> If the data are multichannel, consider using component analysis to isolate the line noise components and regress them out
1. quick PSD to double check which notch filter (careful with "harmonic" effect in Erlacher_new!)
> done (noted in `database.csv`)
2. HP filter (cognitive analyses - use 0.5 Hz as in actionlab)
> done
> TODO cagatay: do before pyPREP because sth like ICA happens under the hood (needs checking)
3. downsample to 100 Hz (common)
> done
4. run pyPREP
> TODO: cagatay: pyPREP does sth like ICA?
6. remove all channels but 6 common ones
> done
8. delete bad (burst) time intervals (automatically --> `YASA`?? see #20 )
10. (if auto-deletions take too much LD data - think of another plan)
11. **split to ICA branch:** 2 Hz high pass filter
12. (interpolate removed channels if << 6 remained??)
13. find artifact ICs and remove from mixing matrix - should get rid of microsaccades (check with `YASA`s REM-finder)
14. go back to main branch; apply mixing matrix to 0.5 Hz LP data
15. re-referencing (to hopefully solve the reduced frontal signal due to ICA)
> is there another reason to have reref 2 times? TODO check Mattermost chat again...
17. segmentation etc. as done in prev. LD papers; see #5

**Comment by nicoa47** [comment]
new info from Mark: better fewer steps than more (avoid overcleaning)
- for example: no ICA, more semi-automatic things

**Comment by nicoa47** [comment]
replaced with #50

**Comment by caghangir-1** [comment]
We are not going to use ICA or notch-filtering and different sources suggest different methods. It is a vicious circle and headache. Samran's preprocessing is too complicated and at the end how can we make sure if we are not overcleaning? If you have no idea of proving that "we do not remove information processing during lucid dreaming which will provide us significant p-values contrasting with the regular REM sleep" then we will basically get fucked, and go back to preprocessing.

**Comment by nicoa47** [comment]
agree!

**Comment by nicoa47** [comment]
agree --> not a planned analysis anymore
