### ISSUE TITLE
how many channels required/preferable for PREP/re-referencing?

### ISSUE THREAD

**Issue by nicoa47** [nicoa47/LDEEG#22]
see Mattermost:
> with regards to [#referencing](https://mattermost.socsci.ru.nl/sleep-memory/channels/special-topics-for-high-density-eegs#): it is a bit tricky. Average referencing is preferred as other references put emphasis on nearby or distant electrodes, so it is better with average  referencing, if the data is collected from evenly distributed electrodes over the scalp. The number of channels: [@Adelhöfer, N. (Nico)]() , I have seen papers using 19 channels as well. But if I remember correctly, 32 is the least recommended, but distributed over the scalp. I will have to find paper where the comparisons were made. And the results doesn't improve much with more than 64 channels. With more channels, it only helps in way that after removing bad channels, data would still likely have >= 64 channels.

**Comment by caghangir-1** [comment]
It's about RANSAC method that requires at least 19-channels for interpolating the bad channels. It is a flag of the pyPREP and when you make it "False" you can use pyPREP even with 2-channels. So, I am already successfully use pyPREP with 6-channels. The only problem occurs when pyPREP determine the whole channels are bad. Then, it gives you some indication that you that data is contaminated and just exclude it (alternative way of data quality assessment).
