### ISSUE TITLE
Scrape methods from mega-analysis papers

### ISSUE THREAD

**Issue by nicoa47** [nicoa47/LDEEG#41]
see here:
https://www.sciencedirect.com/science/article/pii/S1053811919309528
https://www.sciencedirect.com/science/article/pii/S1053811919306366

**Comment by caghangir-1** [comment]
There are multiple sources that we already get the information regarding to preprocessing. If the methods are related to preprocessing then mega-analysis is irrelevant now. I already scraped robust z-score normalization from there but that's it from my side.

**Comment by nicoa47** [comment]
you are right, I hoped for more detailed explanation in the second paper about hierarchical GLM, but it's more about disentangling cognitive effects from thousands of papers. So --> close, but issue #12 holds even more
