### ISSUE TITLE
improve code efficiency

### ISSUE THREAD

**Issue by nicoa47** [nicoa47/LDEEG#43]
e.g. via:
- replacing for-loops (with numpy array functions or at least list comprehensions)
    - sacrifices readability --> add comments!
- use preload function only when necessary
- store and load annotated features in init; only re-compute if explicit call later
- ... ?

**Comment by caghangir-1** [comment]
This is a corporate aim, we are not a corporation. Besides, computationally expensive methods are always built-in functions but not our miserable list comprehensions. It doesn't influence the calculation time.
