### ISSUE TITLE
scrape and document methods from papers by Voss, Dodet, Baird

### ISSUE THREAD

**Issue by nicoa47** [nicoa47/LDEEG#5]

**Comment by caghangir-1** [comment]
> feedback from @caghangir-1 :
> 
>     * how does performed task during analyzed LD segment deviate from anticipated task during analyzed LD segment?
> 
> 
> > Anticipate=before actual performing (so we would expect a preparatory/memory component overlaid over the lucidity brain componen5)
> 
>     * what could we add as a criteria is sample size (number of subjects)
> 
>     * another criteria would be preprocessing protocol.
> 
> 
> > I thought about preprocessing, but it would explode the table (different orders of steps, not all done) but I think about adding 2 or 3 comparible points.
> 
>     * What we now from LR2 is extreme eye movements. For instance, Baird et. al. performed non-stop LRLRLR.... during lucid dreaming as a task which generated non-stop EOG artifacts during lucid dreaming which creates its own complexity of EEG to contrast from baseline REM sleep. We could add one YES, NO criteria about if LD task contains ocular muscle activity or ocular free activity.

**Comment by nicoa47** [comment]
added (to Overleaf MS): number of subjects and cleaning of eye movement artifacts. close.
