### ISSUE TITLE
extract robust z scoring from old code base

### ISSUE THREAD

**Issue by nicoa47** [nicoa47/LDEEG#52]

**Comment by nicoa47** [comment]
**Robust z-score normalization algorithm:**

 def robustZScore(self, raw):
        
        channel_amount = len(raw._data)
        raw_robustzscore = raw.copy()
        
        for i in range(channel_amount):
            MAD = np.median(np.abs(raw._data[i] - np.median(raw._data[i])))
            raw_robustzscore._data[i] = 0.6745 * (raw._data[i] - np.median(raw._data[i])) / MAD
            
        return raw_robustzscore

**Comment by nicoa47** [comment]
implement the code to LDEEG codebase

**Comment by caghangir-1** [comment]
Done
