### ISSUE TITLE
attempt to fix discarded datasets

### ISSUE THREAD

**Issue by caghangir-1** [nicoa47/LDEEG#75]
These nights are discarded due to various reasons:

1) Jarrod Dataset:
   - 1_VR_P261_HASHTAG_NOFILTER_06 : lucid dream segment does not contain proper LRLR signals both for initiation and finish.
   - 2_VR_P261_HASHTAG_NOFILTER_07:  lucid dream segment does not contain proper LRLR signals both for initiation and finish.
2) FILD Dataset:
   - 3_FILD20_n1: volume conduction or similar effects intoxicated channels so channels are substantially similar and interpolate is inapplicable regardingly.
3) Sergio Dataset: whole data is discarded due to the fact that the whole lucid dreaming segment is just non-stop LRLR and so much EOG reflections on EEG are very high likely will not match with the other datasets at all.
   - 0_0004401
   - 1_Luane 2
4) Erlacher new data:
   - 1_tu: almost the whole EEG is corrupted by constant, complex line noise.

**Comment by nicoa47** [comment]
on my part:

**sub-vic_yesLD_session1 AND Vic_BCI_morningnap2_morningnapsession0:**
- combination of (for me) unrecoverable dream report audio (noise + intense volume differences) AND very unclear LRLRs from single HEOG channel, if any  

what I've tried:
- Reaper [FIR-based noise reduction](https://www.youtube.com/watch?v=knDG8qYkR1A)
- Reaper playing with EQing
- Reaper normalizing while disregarding the "plosives"
- try to infer semantics from context
- [AI-based vocal extraction](splitter.ai)

what could be tried next, if important:
- @caghangir-1 can try to make the audio comprehensible
- the times of recorded audio (would need files to be still on local lab PC!!) could guide the LRLR times
