### ISSUE TITLE
inspect Epoched data

### ISSUE THREAD

**Issue by caghangir-1** [nicoa47/LDEEG#81]
Right after preprocessing, we are epoching the data with 4 seconds segments in addition to 2 seconds of overlapping. The aim here is to check epoched data if the preprocessing worked promptly or failed. In this regard, I added one column to approve or concerned about the preprocessed + epoched data in the meta-data file on google drive: https://docs.google.com/spreadsheets/d/1U7xDdF5MngjDVfL4Shj61X5ly4CHky_b/edit#gid=1539025030

What are the corruption essences of a given epoch to be discarded:
* Obvious eye movement artefact
* Destructive high-frequency bursts--spiking amplitudes combined with gamma bursts are not considered as a neural activity but uncleaned sweat and/or movement artefacts.
* Periodic line noises.
* In high-density EEGs, at least a handful amount of EEG channels must be corrupted (e.g. 20%).

**Comment by nicoa47** [comment]
renamed as an issue and closed since apparently done
